
class IndianLocations {
  static final Map<String, List<String>> statesAndCities = {
    'Andhra Pradesh': [
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Kadapa',
      'Rajahmundry',
      'Tirupati',
      'Kakinada',
      'Anantapur',
      'Eluru',
      'Ongole',
      'Chittoor',
      'Machilipatnam',
      'Adoni',
      'Proddatur',
      'Hindupur',
      'Bhimavaram',
      'Madanapalle',
      'Guntakal',
      'Srikakulam',
      'Dharmavaram',
      'Gudivada',
      'Narasaraopet',
      'Tadipatri',
      'Tenali',
      'Chilakaluripet',
      'Parvathipuram',
      'Vizianagaram',
      'Tadepalligudem',
      'Amaravati'
    ],
    'Arunachal Pradesh': [
      'Itanagar',
      'Naharlagun',
      'Pasighat',
      'Tawang',
      'Ziro',
      'Bomdila',
      'Roing',
      'Tezu',
      'Namsai',
      'Along',
      'Daporijo',
      'Anini',
      'Yingkiong',
      'Seppa',
      'Khonsa',
      'Changlang',
      'Aalo',
      'Hawai',
      'Longding',
      'Koloriang',
      'Pangin',
      'Basar',
      'Mechuka',
      'Dirang',
      'Tuting',
      'Sagalee',
      'Tali',
      'Palin',
      'Nyapin',
      'Hayuliang'
    ],
    'Assam': [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
      'Karimganj',
      'Hailakandi',
      'Bongaigaon',
      'Dhubri',
      'Diphu',
      'North Lakhimpur',
      'Goalpara',
      'Barpeta',
      'Sivasagar',
      'Kokrajhar',
      'Golaghat',
      'Dhemaji',
      'Morigaon',
      'Lanka',
      'Hojai',
      'Mangaldoi',
      'Nalbari',
      'Duliajan',
      'Namrup',
      'Rangia',
      'Margherita',
      'Digboi',
      'Mariani',
      'Naharkatia',
      'Marigaon',
      'Bamboo Flat',
      'Garacharma',
      'Prothrapur',
      'Hope Town',
      'Nimbutala'
    ],
    'Bihar': [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Arrah',
      'Begusarai',
      'Katihar',
      'Munger',
      'Chhapra',
      'Bettiah',
      'Saharsa',
      'Sasaram',
      'Hajipur',
      'Dehri',
      'Bihar Sharif',
      'Siwan',
      'Motihari',
      'Nawada',
      'Bagaha',
      'Buxar',
      'Kishanganj',
      'Sitamarhi',
      'Jamalpur',
      'Jehanabad',
      'Aurangabad',
      'Lakhisarai',
      'Araria',
      'Madhubani',
      'Supaul',
      'Samastipur',
      'Mokama',
      'Gopalganj',
      'Madhepura',
      'Barh',
      'Khagaria',
      'Jammui',
      'Banka'
    ],
    'Chhattisgarh': [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Durg',
      'Rajnandgaon',
      'Jagdalpur',
      'Raigarh',
      'Ambikapur',
      'Mahasamund',
      'Dhamtari',
      'Chirmiri',
      'Bhatapara',
      'Dalli-Rajhara',
      'Naila Janjgir',
      'Tilda Newra',
      'Kawardha',
      'Kondagaon',
      'Kanker',
      'Dongargarh',
      'Birgaon',
      'Bemetara',
      'Mungeli',
      'Balod',
      'Takhatpur',
      'Gidam',
      'Pathalgaon',
      'Khairagarh',
      'Sakti',
      'Ratanpur',
      'Baloda Bazar'
    ],
    'Goa': [
      'Panaji',
      'Margao',
      'Vasco da Gama',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Curchorem',
      'Sanquelim',
      'Cuncolim',
      'Quepem',
      'Pernem',
      'Valpoi',
      'Canacona',
      'Sanguem',
      'Mormugao',
      'Dharbandora',
      'Calangute',
      'Candolim',
      'Anjuna',
      'Colva',
      'Benaulim',
      'Arambol',
      'Mandrem',
      'Aldona',
      'Vagator',
      'Cortalim',
      'Morjim',
      'Agonda',
      'Porvorim'
    ],
    'Gujarat': [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Gandhinagar',
      'Junagadh',
      'Anand',
      'Bharuch',
      'Nadiad',
      'Mehsana',
      'Morbi',
      'Surendranagar',
      'Patan',
      'Gandhidham',
      'Bhuj',
      'Porbandar',
      'Palanpur',
      'Valsad',
      'Vapi',
      'Navsari',
      'Veraval',
      'Godhra',
      'Dahod',
      'Botad',
      'Amreli',
      'Deesa',
      'Jetpur',
      'Kalol',
      'Gondal',
      'Dharampur',
      'Vyara',
      'Wadhwan',
      'Ankleshwar',
      'Kadi',
      'Petlad',
      'Sidhpur',
      'Una',
      'Unjha'
    ],
    'Haryana': [
      'Faridabad',
      'Gurgaon',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
      'Panchkula',
      'Bhiwani',
      'Sirsa',
      'Bahadurgarh',
      'Jind',
      'Thanesar',
      'Kaithal',
      'Rewari',
      'Palwal',
      'Hansi',
      'Narnaul',
      'Fatehabad',
      'Gohana',
      'Tohana',
      'Narwana',
      'Charkhi Dadri',
      'Shahbad',
      'Mandi Dabwali',
      'Pehowa',
      'Samalkha',
      'Pinjore',
      'Ladwa',
      'Mahendragarh',
      'Taraori',
      'Assandh',
      'Sohna',
      'Safidon',
      'Beri',
      'Naraingarh',
      'Ratia'
    ],
    'Himachal Pradesh': [
      'Shimla',
      'Mandi',
      'Dharamshala',
      'Solan',
      'Kullu',
      'Bilaspur',
      'Chamba',
      'Hamirpur',
      'Una',
      'Nahan',
      'Palampur',
      'Baddi',
      'Paonta Sahib',
      'Sundernagar',
      'Parwanoo',
      'Rohroo',
      'Joginder Nagar',
      'Rampur',
      'Kangra',
      'Nurpur',
      'Dalhousie',
      'Manali',
      'Kasauli',
      'Kalpa',
      'Keylong',
      'Narkanda',
      'Banjar',
      'Jawali',
      'Dehra',
      'Arki',
      'Nadaun',
      'Nagrota Bagwan',
      'Sujanpur',
      'Mandi Gobindgarh'
    ],
    'Jharkhand': [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro',
      'Hazaribagh',
      'Deoghar',
      'Giridih',
      'Ramgarh',
      'Phusro',
      'Medininagar',
      'Chirkunda',
      'Gumla',
      'Dumka',
      'Chaibasa',
      'Jamtara',
      'Godda',
      'Sahibganj',
      'Lohardaga',
      'Chakradharpur',
      'Madhupur',
      'Chatra',
      'Garhwa',
      'Simdega',
      'Mihijam',
      'Latehar',
      'Pakur',
      'Khunti',
      'Koderma',
      'Bundu',
      'Pakaur',
      'Barhi',
      'Rajmahal',
      'Chandil',
      'Jasidih',
      'Jharia',
      'Chass',
      'Saraikela'
    ]
  };

  static final Map<String, List<String>> statesAndCitiesPart2 = {
    'Karnataka': [
      'Bangalore',
      'Mysore',
      'Hubli-Dharwad',
      'Mangalore',
      'Belgaum',
      'Gulbarga',
      'Davanagere',
      'Bellary',
      'Bijapur',
      'Shimoga',
      'Tumkur',
      'Raichur',
      'Bidar',
      'Hassan',
      'Robertson Pet',
      'Udupi',
      'Hospet',
      'Chitradurga',
      'Bagalkot',
      'Haveri',
      'Gadag-Betigeri',
      'Ranebennur',
      'Karwar',
      'Chikmagalur',
      'Bhadravati',
      'Gokak',
      'Mandya',
      'Madikeri',
      'Chikkaballapur',
      'Kolar',
      'Ramanagaram',
      'Koppal',
      'Gangawati',
      'Yadgir',
      'Channagiri',
      'Tiptur'
    ],
    'Kerala': [
      'Thiruvananthapuram',
      'Kochi',
      'Kozhikode',
      'Thrissur',
      'Kollam',
      'Palakkad',
      'Alappuzha',
      'Kannur',
      'Kottayam',
      'Malappuram',
      'Kasaragod',
      'Ponnani',
      'Thalassery',
      'Vatakara',
      'Neyyattinkara',
      'Guruvayur',
      'Changanassery',
      'Perinthalmanna',
      'Chalakudy',
      'Kodungallur',
      'Kayamkulam',
      'Tirur',
      'Thodupuzha',
      'Pathanamthitta',
      'Kanhangad',
      'Nedumangad',
      'Nilambur',
      'Ottappalam',
      'Shornur',
      'Payyanur',
      'Mattannur',
      'Kalpetta',
      'Mananthavady',
      'Thirurangadi',
      'Angamaly'
    ],
    'Madhya Pradesh': [
      'Bhopal',
      'Indore',
      'Jabalpur',
      'Gwalior',
      'Ujjain',
      'Sagar',
      'Dewas',
      'Satna',
      'Ratlam',
      'Rewa',
      'Murwara',
      'Singrauli',
      'Burhanpur',
      'Khandwa',
      'Bhind',
      'Chhindwara',
      'Guna',
      'Shivpuri',
      'Vidisha',
      'Chhatarpur',
      'Damoh',
      'Mandsaur',
      'Khargone',
      'Neemuch',
      'Pithampur',
      'Hoshangabad',
      'Itarsi',
      'Sehore',
      'Betul',
      'Seoni',
      'Datia',
      'Nagda',
      'Dhanpuri',
      'Morena',
      'Jaora',
      'Bina',
      'Harda'
    ],
    'Maharashtra': [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Thane',
      'Nashik',
      'Aurangabad',
      'Solapur',
      'Kalyan',
      'Vasai-Virar',
      'Bhiwandi',
      'Amravati',
      'Nanded',
      'Kolhapur',
      'Sangli',
      'Malegaon',
      'Akola',
      'Latur',
      'Dhule',
      'Ahmednagar',
      'Ichalkaranji',
      'Chandrapur',
      'Parbhani',
      'Jalgaon',
      'Ulhasnagar',
      'Bhusawal',
      'Satara',
      'Panvel',
      'Beed',
      'Yavatmal',
      'Wardha',
      'Gondia',
      'Barshi',
      'Achalpur',
      'Osmanabad',
      'Nandurbar',
      'Hinganghat'
    ],
    'Manipur': [
      'Imphal',
      'Thoubal',
      'Kakching',
      'Ukhrul',
      'Chandel',
      'Churachandpur',
      'Bishnupur',
      'Senapati',
      'Jiribam',
      'Moreh',
      'Lilong',
      'Mayang Imphal',
      'Kangpokpi',
      'Yairipok',
      'Sugnu',
      'Moirang',
      'Nambol',
      'Ningthoukhong',
      'Oinam',
      'Singhat',
      'Samurou',
      'Wangjing',
      'Heingang',
      'Sekmai',
      'Kwakta',
      'Pherzawl',
      'Nungba',
      'Kamjong',
      'Noney',
      'Tamenglong'
    ],
    'Meghalaya': [
      'Shillong',
      'Tura',
      'Jowai',
      'Nongstoin',
      'Williamnagar',
      'Baghmara',
      'Resubelpara',
      'Mairang',
      'Nongpoh',
      'Khliehriat',
      'Mawlai',
      'Cherrapunji',
      'Madanrting',
      'Laban',
      'Mawkyrwat',
      'Ampati',
      'Mankachar',
      'Pynthorumkhrah',
      'Umroi',
      'Nongthymmai',
      'Mawsynram',
      'Lawsohtun',
      'Sohra',
      'Ladrymbai',
      'Rynjah',
      'Umpling',
      'Mawpat',
      'Mawryngkneng',
      'Sngithiang',
      'Mendipathar'
    ],
    'Mizoram': [
      'Aizawl',
      'Lunglei',
      'Saiha',
      'Champhai',
      'Kolasib',
      'Serchhip',
      'Lawngtlai',
      'Mamit',
      'Khawzawl',
      'Hnahthial',
      'Saitual',
      'Lengpui',
      'Thenzawl',
      'North Vanlaiphai',
      'Zawlnuam',
      'Darlawn',
      'Khawhai',
      'Bairabi',
      'Vairengte',
      'Bilkhawthlir',
      'Biate',
      'Tlabung',
      'Kawrthah',
      'Phuldungsei',
      'Rawpuichhip',
      'Zobawk',
      'Thingdawl',
      'Keifang',
      'Khawruhlian',
      'Bungtlang'
    ],
    'Nagaland': [
      'Kohima',
      'Dimapur',
      'Mokokchung',
      'Tuensang',
      'Wokha',
      'Zunheboto',
      'Mon',
      'Phek',
      'Kiphire',
      'Longleng',
      'Peren',
      'Chumukedima',
      'Tseminyu',
      'Mangkolemba',
      'Changtongya',
      'Tuli',
      'Noklak',
      'Shamator',
      'Pfutsero',
      'Jalukie',
      'Aboi',
      'Tening',
      'Medziphema',
      'Longkhim',
      'Tobu',
      'Naginimora',
      'Tizit',
      'Chozuba',
      'Aghunato',
      'Meluri'
    ],
    'Odisha': [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Berhampur, Puri',
      'Sambalpur',
      'Balasore',
      'Bhadrak',
      'Baripada',
      'Jharsuguda',
      'Jeypore',
      'Bargarh',
      'Rayagada',
      'Paradip',
      'Bhawanipatna',
      'Dhenkanal',
      'Barbil',
      'Kendujhar',
      'Sunabeda',
      'Brajarajnagar',
      'Jatni',
      'Kendrapara',
      'Angul',
      'Balangir',
      'Nabarangpur',
      'Koraput',
      'Phulbani',
      'Jagatsinghpur',
      'Nayagarh',
      'Malkangiri',
      'Sonepur',
      'Talcher',
      'Boudh',
      'Nuapada'
    ],
    'Punjab': [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Mohali',
      'Pathankot',
      'Hoshiarpur',
      'Batala',
      'Moga',
      'Malerkotla',
      'Khanna',
      'Phagwara',
      'Muktsar',
      'Barnala',
      'Rajpura',
      'Firozpur',
      'Kapurthala',
      'Faridkot',
      'Sangrur',
      'Fatehgarh Sahib',
      'Gurdaspur',
      'Abohar',
      'Mansa',
      'Nabha',
      'Malout',
      'Fazilka',
      'Zirakpur',
      'Samana',
      'Tarn Taran',
      'Jagraon',
      'Sunam',
      'Dhuri',
      'Nawanshahr',
      'Rupnagar'
    ],
    'Rajasthan': [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Bharatpur',
      'Sri Ganganagar',
      'Sikar',
      'Pali',
      'Tonk',
      'Kishangarh',
      'Beawar',
      'Hanumangarh',
      'Dhaulpur',
      'Gangapur City',
      'Sawai Madhopur',
      'Churu',
      'Jhunjhunu',
      'Nagaur',
      'Hindaun',
      'Bhiwadi',
      'Bundi',
      'Sujangarh',
      'Banswara',
      'Sagwara',
      'Makrana',
      'Nokha',
      'Pushkar',
      'Balotra',
      'Dungarpur',
      'Chittorgarh',
      'Rajsamand'
    ],
    'Sikkim': [
      'Gangtok',
      'Namchi',
      'Gyalshing',
      'Mangan',
      'Rangpo',
      'Singtam',
      'Jorethang',
      'Ravangla',
      'Soreng',
      'Nayabazar',
      'Rongli',
      'Rhenock',
      'Pelling',
      'Pakyong',
      'Ranipool',
      'Majitar',
      'Legship',
      'Chungthang',
      'Lachung',
      'Lachen',
      'Yuksom',
      'Melli',
      'Dentam',
      'Dzongu',
      'Dikchu',
      'Namthang',
      'Yangang',
      'Temi',
      'Kaluk',
      'Rinchenpong'
    ],
    'Tamil Nadu': [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tirunelveli',
      'Tiruppur',
      'Erode',
      'Vellore',
      'Thoothukudi',
      'Nagercoil',
      'Thanjavur',
      'Dindigul',
      'Cuddalore',
      'Kancheepuram',
      'Tiruvannamalai',
      'Karur',
      'Udhagamandalam',
      'Hosur',
      'Rajapalayam',
      'Ambur',
      'Kumbakonam',
      'Sivakasi',
      'Pudukkottai',
      'Neyveli',
      'Nagapattinam',
      'Viluppuram',
      'Tiruchengode',
      'Vaniyambadi',
      'Theni',
      'Karaikudi',
      'Virudhunagar',
      'Pollachi',
      'Tiruvarur',
      'Namakkal',
      'Krishnagiri'
    ],
    'Telangana': [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Karimnagar',
      'Khammam',
      'Ramagundam',
      'Mahbubnagar',
      'Nalgonda',
      'Adilabad',
      'Suryapet',
      'Miryalaguda',
      'Jagtial',
      'Mancherial',
      'Siddipet',
      'Kothagudem',
      'Bodhan',
      'Kamareddy',
      'Wanaparthy',
      'Nirmal',
      'Sangareddy',
      'Vikarabad',
      'Medak',
      'Tandur',
      'Sircilla',
      'Narayanpet',
      'Gadwal',
      'Jangaon',
      'Mahabubabad',
      'Bellampalle',
      'Bhadrachalam',
      'Bhongir',
      'Medchal',
      'Zahirabad',
      'Nagarkurnool',
      'Palwancha',
      'Armoor'
    ],
    'Tripura': [
      'Agartala',
      'Udaipur',
      'Dharmanagar',
      'Kailasahar',
      'Belonia',
      'Ambassa',
      'Khowai',
      'Teliamura',
      'Sabroom',
      'Amarpur',
      'Sonamura',
      'Bishalgarh',
      'Melaghar',
      'Ranirbazar',
      'Mohanpur',
      'Jogendranagar',
      'Kamalpur',
      'Kumarghat',
      'Jirania',
      'Panisagar',
      'Jampuijala',
      'Santirbazar',
      'Matabari',
      'Amarpur',
      'Kakraban',
      'Kalyanpur',
      'Madhupur',
      'Mandai',
      'Champahowar',
      'Boxanagar'
    ],
    'Uttarakhand': [
      'Dehradun',
      'Haridwar',
      'Roorkee',
      'Haldwani',
      'Rudrapur',
      'Kashipur',
      'Rishikesh',
      'Pithoragarh',
      'Ramnagar',
      'Khatima',
      'Manglaur',
      'Nainital',
      'Mussoorie',
      'Jaspur',
      'Bajpur',
      'Almora',
      'Kotdwar',
      'Tanakpur',
      'Tehri',
      'Pauri',
      'Bageshwar',
      'Gopeshwar',
      'Champawat',
      'Uttarkashi',
      'Sitarganj',
      'Jhabrera',
      'Laksar',
      'Lansdowne',
      'Ranikhet',
      'Dugadda'
    ],
    'Uttar Pradesh': [
      'Lucknow',
      'Kanpur',
      'Varanasi',
      'Agra',
      'Prayagraj',
      'Meerut',
      'Bareilly',
      'Aligarh',
      'Moradabad',
      'Saharanpur',
      'Gorakhpur',
      'Noida',
      'Firozabad',
      'Loni',
      'Jhansi',
      'Muzaffarnagar',
      'Mathura',
      'Rampur',
      'Shahjahanpur',
      'Etawah',
      'Farrukhabad',
      'Ayodhya',
      'Bulandshahr',
      'Hapur',
      'Ghazipur',
      'Sultanpur',
      'Azamgarh',
      'Unnao',
      'Rae Bareli',
      'Orai',
      'Bahraich',
      'Jaunpur',
      'Fatehpur',
      'Banda',
      'Mirzapur',
      'Sitapur',
      'Barabanki',
      'Mau',
      'Mainpuri',
      'Chandausi',
      'Fatehgarh',
      'Ballia',
      'Deoria',
      'Gonda',
      'Basti',
      'Sambhal',
      'Amroha',
      'Hardoi',
      'Bijnor',
      'Budaun',
      'Shikohabad',
      'Shamli',
      'Khurja',
      'Kasganj',
      'Auraiya',
      'Greater Noida',
      'Etah',
      'Akbarpur',
      'Lalitpur'
    ],
    'West Bengal': [
      'Kolkata',
      'Howrah',
      'Durgapur',
      'Asansol',
      'Siliguri',
      'Bardhaman',
      'Malda',
      'Baharampur',
      'Habra',
      'Kharagpur',
      'Shantipur',
      'Dankuni',
      'Dhulian',
      'Ranaghat',
      'Haldia',
      'Raiganj',
      'Krishnanagar',
      'Nabadwip',
      'Medinipur',
      'Jalpaiguri',
      'Balurghat',
      'Basirhat',
      'Bankura',
      'Chakdaha',
      'Darjeeling',
      'Alipurduar',
      'Purulia',
      'Jangipur',
      'Bangaon',
      'Cooch Behar',
      'Bolpur',
      'Kanthi',
      'Srirampore',
      'Barasat',
      'Krishnapur',
      'Naihati',
      'Barrackpore',
      'Kalna',
      'Rishra',
      'Uttarpara'
    ],
    'Andaman and Nicobar Islands': [
      'Port Blair',
      'Bamboo Flat',
      'Garacharma',
      'Prothrapur',
      'Rangat',
      'Mayabunder',
      'Diglipur',
      'Little Andaman',
      'Car Nicobar',
      'Kamorta',
      'Havelock Island',
      'Neil Island',
      'Long Island',
      'Hut Bay',
      'Campbell Bay',
      'Teressa',
      'Katchal',
      'Nicobar',
      'Ross Island',
      'North Passage Island'
    ],
    'Chandigarh': [
      'Chandigarh',
      'Manimajra',
      'Burail',
      'Attawa',
      'Badheri',
      'Buterla',
      'Dadu Majra',
      'Dhanas',
      'Daria',
      'Grain Market',
      'Hallomajra',
      'Industrial Area',
      'Kaimbwala',
      'Kajheri',
      'Khuda Alisher',
      'Khuda Jassu',
      'Khuda Lahora',
      'Maloya',
      'Palsora',
      'Ram Darbar'
    ],
    'Dadra and Nagar Haveli': [
      'Silvassa',
      'Amli',
      'Dadra',
      'Naroli',
      'Samarvarni',
      'Dudhani',
      'Khanvel',
      'Randha',
      'Athola',
      'Kilvani',
      'Luhari',
      'Mashat',
      'Rakholi',
      'Sindoni',
      'Velugam',
      'Vasona',
      'Tighra',
      'Surangi',
      'Sili',
      'Kherdi'
    ],
    'Daman and Diu': [
      'Daman',
      'Diu',
      'Ghoghla',
      'Fudam',
      'Vanakbara',
      'Bhimpore',
      'Dunetha',
      'Nani Daman',
      'Moti Daman',
      'Kadaiya',
      'Varkund',
      'Kachigam',
      'Marwad',
      'Devka',
      'Patlara',
      'Bucharwada',
      'Dabhel',
      'Zari'
    ],
    'Delhi': [
      'New Delhi',
      'North Delhi',
      'South Delhi',
      'East Delhi',
      'West Delhi',
      'Central Delhi',
      'North East Delhi',
      'South West Delhi',
      'North West Delhi',
      'Shahdara',
      'Dwarka',
      'Rohini',
      'Pitampura',
      'Vikaspuri',
      'Janakpuri',
      'Vasant Kunj',
      'Connaught Place',
      'Karol Bagh',
      'Chandni Chowk',
      'Saket',
      'Hauz Khas',
      'Laxmi Nagar',
      'Paharganj',
      'Rajouri Garden',
      'Mayur Vihar',
      'Preet Vihar',
      'Model Town',
      'Kalkaji',
      'Lajpat Nagar',
      'Greater Kailash',
      'Malviya Nagar',
      'Punjabi Bagh',
      'Krishna Nagar',
      'Dilshad Garden',
      'Paschim Vihar',
      'Narela',
      'Bawana',
      'Uttam Nagar',
      'Najafgarh'
    ],
    'Lakshadweep': [
      'Kavaratti',
      'Agatti',
      'Amini',
      'Androth',
      'Bangaram',
      'Bitra',
      'Chetlat',
      'Kadmat',
      'Kalpeni',
      'Kiltan',
      'Minicoy',
      'Suheli',
      'Cheriyam',
      'Tinakkara',
      'Parali'
    ],
    'Puducherry': [
      'Puducherry',
      'Karaikal',
      'Yanam',
      'Mahe',
      'Ozhukarai',
      'Villianur',
      'Ariyankuppam',
      'Bahour',
      'Thirumalairayanpattinam',
      'Thirubhuvanai',
      'Kurumbapet',
      'Lawspet',
      'Muthialpet',
      'Reddiarpalayam',
      'Thirukkanur',
      'Kottucherry',
      'Nedungadu',
      'Neravy',
      'Thirunallar',
      'Kottakuppam'
    ],
    'Ladakh': [
      'Leh',
      'Kargil',
      'Nubra',
      'Zanskar',
      'Diskit',
      'Khaltse',
      'Drass',
      'Sankoo',
      'Padum',
      'Hundar',
      'Nyoma',
      'Skurbuchan',
      'Khalatse',
      'Turtuk',
      'Chuchot',
      'Kharu',
      'Tangtse',
      'Shyok',
      'Sumoor',
      'Saspol'
    ],
    'Jammu and Kashmir': [
      'Srinagar',
      'Jammu',
      'Anantnag',
      'Baramulla',
      'Kathua',
      'Udhampur',
      'Kupwara',
      'Pulwama',
      'Sopore',
      'Poonch',
      'Rajouri',
      'Bijbehara',
      'Bandipore',
      'Ganderbal',
      'Doda',
      'Handwara',
      'Kulgam',
      'Kishtwar',
      'Ramban',
      'Bhaderwah',
      'Samba',
      'Budgam',
      'Shopian',
      'Reasi',
      'Tral',
      'Achabal',
      'Pahalgam',
      'Awantipora',
      'Gulmarg',
      'Sumbal'
    ]
  };

// Helper methods for accessing the data
  static List<String> getStates() {
    final allStates = {...statesAndCities, ...statesAndCitiesPart2}.keys.toList();
    allStates.sort();
    return allStates;
  }

  static List<String> getCitiesForState(String state) {
    final cities = statesAndCities[state] ?? statesAndCitiesPart2[state] ?? [];
    return List<String>.from(cities)..sort();
  }

// Additional helper methods
  static bool isValidState(String state) {
    return statesAndCities.containsKey(state);
  }

  static bool isValidCity(String state, String city) {
    List<String>? cities = statesAndCities[state];
    return cities != null && cities.contains(city);
  }

  static int getTotalStates() {
    return statesAndCities.length;
  }

  static int getTotalCitiesForState(String state) {
    return statesAndCities[state]?.length ?? 0;
  }

  static Map<String, int> getCitiesCountByState() {
    Map<String, int> citiesCount = {};
    statesAndCities.forEach((state, cities) {
      citiesCount[state] = cities.length;
    });
    return citiesCount;
  }
}

// Extension to use with the dropdowns
extension StringExtension on String {
  String get inCaps => '${this[0].toUpperCase()}${substring(1)}';
  String get allInCaps => toUpperCase();
  String get capitalizeFirstOfEach =>
      split(" ").map((str) => str.inCaps).join(" ");
}
